name: Build and Release Packages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (leave empty for auto from meson.build)"
        required: false
        type: string
      release_body:
        description: "Release body (leave empty to use CHANGELOG.md or generate from git commits)"
        required: false
        type: string
      release_body_source:
        description: "Release body source (auto, changelog, git_commits)"
        required: false
        default: "auto"
        type: choice
        options:
          - auto
          - changelog
          - git_commits

permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION=$(grep -o "version: '[^']*'" meson.build | sed "s/version: '\([^']*\)'/\1/")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

  generate-release-body:
    needs: get-version
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.generate-body.outputs.release_body }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Body
        id: generate-body
        run: |
          # If release body is provided manually, use it
          if [ -n "${{ github.event.inputs.release_body }}" ]; then
            {
              printf '%s\n' "release_body<<EOF"
              printf '%s\n' "${{ github.event.inputs.release_body }}"
              printf '%s\n' "EOF"
            } >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Determine source
          SOURCE="${{ github.event.inputs.release_body_source }}"
          if [ "$SOURCE" = "auto" ]; then
            if [ -f "CHANGELOG.md" ]; then
              SOURCE="changelog"
            else
              SOURCE="git_commits"
            fi
          fi

          # Build release body into a temporary file using real newlines,
          # then write it once to the GitHub Actions output to avoid
          # literal "\n" sequences appearing in the final release body.
          TMP_RELEASE=$(mktemp)
          # Ensure cleanup on exit
          trap 'rm -f "$TMP_RELEASE"' EXIT

          case "$SOURCE" in
            "changelog")
              if [ -f "CHANGELOG.md" ]; then
                printf '%s\n\n' "## Changes" >> "$TMP_RELEASE"
                # Extract latest version section from CHANGELOG.md
                awk '
                  /^## \[v.*\]/ { if (++count > 1) exit; next }
                  count == 1 && /^###/ { in_section = 1 }
                  count == 1 && in_section && /^---/ { exit }
                  count == 1 && in_section { print }
                ' CHANGELOG.md >> "$TMP_RELEASE"
              else
                printf '%s\n' "CHANGELOG.md not found, falling back to git commits" >> "$TMP_RELEASE"
                SOURCE="git_commits"
              fi
              ;;
          esac

          if [ "$SOURCE" = "git_commits" ]; then
            printf '%s\n\n' "## Changes" >> "$TMP_RELEASE"

            # Get previous tag
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")

            if [ -n "$PREVIOUS_TAG" ]; then
              printf '%s\n' "### New Features" >> "$TMP_RELEASE"
              git log --pretty=format:"%s" --grep="^feat:" --grep="^add:" --grep="^new:" $PREVIOUS_TAG..HEAD | sed 's/^/- /' >> "$TMP_RELEASE"
              printf '\n' >> "$TMP_RELEASE"

              printf '%s\n' "### Bug Fixes" >> "$TMP_RELEASE"
              git log --pretty=format:"%s" --grep="^fix:" --grep="^bug:" $PREVIOUS_TAG..HEAD | sed 's/^/- /' >> "$TMP_RELEASE"
              printf '\n' >> "$TMP_RELEASE"

              printf '%s\n' "### Other Changes" >> "$TMP_RELEASE"
              git log --pretty=format:"%s" $PREVIOUS_TAG..HEAD | grep -v -E "^(feat|add|new|fix|bug):" | sed 's/^/- /' >> "$TMP_RELEASE"
              printf '\n' >> "$TMP_RELEASE"
            else
              printf '%s\n' "### Recent Changes" >> "$TMP_RELEASE"
              git log --oneline --since="1 week ago" --pretty=format:"%s" | sed 's/^/- /' >> "$TMP_RELEASE"
              printf '\n' >> "$TMP_RELEASE"
            fi
          fi

          # Add package information
          printf '%s\n' "### Package Downloads" >> "$TMP_RELEASE"
          printf '%s\n' "- **Flatpak**: `org.badkiko.sofl.flatpak`" >> "$TMP_RELEASE"
          printf '%s\n' "- **Debian/Ubuntu**: `sofl_${{ needs.get-version.outputs.version }}_all.deb`" >> "$TMP_RELEASE"
          printf '%s\n\n' "- **Arch Linux**: `.pkg.tar.zst` binary package" >> "$TMP_RELEASE"

          # Installation instructions block
          cat >> "$TMP_RELEASE" <<'EOT'
          ### Installation Instructions

          **Flatpak:**
          ```bash
          flatpak install --user org.badkiko.sofl.flatpak
          ```

          **Debian/Ubuntu:**
          ```bash
          sudo dpkg -i sofl_${{ needs.get-version.outputs.version }}_all.deb
          sudo apt install -f
          ```

          **Arch Linux:**
          ```bash
          sudo pacman -U sofl-*.pkg.tar.zst
          ```
          EOT

          # Single redirection: write the multi-line output safely
          {
            printf '%s\n' "release_body<<EOF"
            cat "$TMP_RELEASE"
            printf '%s\n' "EOF"
          } >> "$GITHUB_OUTPUT"

  build-flatpak:
    needs: [get-version, generate-release-body]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flatpak dependencies
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder python3-gi python3-gi-cairo git python3-pip gettext

      - name: Setup flatpak
        run: |
          flatpak --version
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak update --appstream --user || true

      - name: Install flatpak runtimes
        run: |
          flatpak install --user --noninteractive flathub org.gnome.Platform//48
          flatpak install --user --noninteractive flathub org.gnome.Sdk//48

      - name: Update version
        run: |
          ./scripts/update_version.sh ${{ needs.get-version.outputs.version }}

      - name: Build Flatpak
        env:
          FLATPAK_BRANCH: stable
        run: |
          mkdir -p dist
          cd packaging/flatpak
          ./build.sh ${{ needs.get-version.outputs.version }} ../../dist

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: sofl-flatpak-${{ needs.get-version.outputs.version }}
          path: dist/org.badkiko.sofl.flatpak

  # build-deb:
  #   needs: [get-version, generate-release-body]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Install dependencies
  #       run: |
  #         sudo apt update
  #         sudo apt install -y meson ninja-build python3-gi python3-gi-cairo gir1.2-gtk-4.0 gir1.2-adw-1 python3-requests python3-pillow python3-cairo python3-psutil python3-xdg dpkg-dev libgtk-4-dev libadwaita-1-dev blueprint-compiler gettext desktop-file-utils
  #
  #     - name: Update version
  #       run: |
  #         ./scripts/update_version.sh ${{ needs.get-version.outputs.version }}
  #
  #     - name: Build Debian package
  #       run: |
  #         mkdir -p "$GITHUB_WORKSPACE/dist"
  #         ./packaging/debian/build.sh ${{ needs.get-version.outputs.version }} "$GITHUB_WORKSPACE/dist"
  #
  #     - name: Upload Debian artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: sofl-deb-${{ needs.get-version.outputs.version }}
  #         path: ${{ github.workspace }}/dist/sofl_${{ needs.get-version.outputs.version }}_all.deb

  # build-arch:
  #   needs: [get-version, generate-release-body]
  #   runs-on: ubuntu-latest
  #   container:
  #     image: archlinux:latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Create builder user for makepkg
  #       run: |
  #         # Create builder user since makepkg doesn't like running as root
  #         if ! id -u builder &>/dev/null; then
  #             useradd -m -s /bin/bash builder
  #             # Give builder user access to project directory
  #             mkdir -p ${{ github.workspace }}
  #             chown -R builder:builder ${{ github.workspace }} || echo "Warning: Could not change ownership, continuing anyway..."
  #         fi
  #
  #     - name: Update system and install dependencies (root)
  #       run: |
  #         pacman -Sy --noconfirm
  #         pacman -S --noconfirm --needed base-devel git meson ninja python python-gobject gtk4 libadwaita python-requests python-pillow python-cairo python-psutil python-pyxdg gobject-introspection blueprint-compiler gettext python-rarfile python-setuptools python-pip
  #
  #     - name: Update version (root)
  #       run: |
  #         ./scripts/update_version.sh ${{ needs.get-version.outputs.version }}
  #
  #     - name: Restore ownership to builder after version update
  #       run: |
  #         chown -R builder:builder ${{ github.workspace }} || echo "Warning: Could not change ownership, continuing anyway..."
  #
  #     - name: Fix git safe directory as builder
  #       run: |
  #         runuser -u builder -- bash -c "git config --global --add safe.directory ${{ github.workspace }}"
  #
  #     - name: Build Arch Linux package as builder
  #       run: |
  #         mkdir -p dist
  #         chown builder:builder dist || echo "Warning: Could not change ownership of dist, continuing anyway..."
  #         runuser -u builder -- bash -c "cd packaging/arch && ./build.sh ${{ needs.get-version.outputs.version }} dist"
  #
  #     - name: Upload Arch package artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: sofl-arch-${{ needs.get-version.outputs.version }}
  #         path: |
  #           dist/*.pkg.tar.zst

  release:
    needs: [get-version, generate-release-body, build-flatpak]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.get-version.outputs.version }}
          name: SOFL v${{ needs.get-version.outputs.version }}
          body: ${{ needs.generate-release-body.outputs.release_body }}
          files: |
            sofl-flatpak-${{ needs.get-version.outputs.version }}/org.badkiko.sofl.flatpak
        #            # sofl-deb-${{ needs.get-version.outputs.version }}/sofl_${{ needs.get-version.outputs.version }}_all.deb
        #            # sofl-arch-${{ needs.get-version.outputs.version }}/*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
