name: Test Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flatpak dependencies
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder

      - name: Setup flatpak
        run: |
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak update --appstream --user || true

      - name: Install flatpak runtimes
        run: |
          flatpak install --user --noninteractive flathub org.gnome.Platform//48
          flatpak install --user --noninteractive flathub org.gnome.Sdk//48

      - name: Test Flatpak build
        run: |
          cd packaging/flatpak
          flatpak-builder --force-clean --user --repo=test-repo --install-deps-from=flathub flatpak-build org.badkiko.sofl.yml --build-only

      - name: Verify Flatpak bundle creation
        run: |
          cd packaging/flatpak
          flatpak build-bundle test-repo org.badkiko.sofl.flatpak org.badkiko.sofl
          ls -la org.badkiko.sofl.flatpak

  test-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build python3-gi python3-gi-cairo gir1.2-gtk-4.0 gir1.2-adw-1 python3-requests python3-pillow python3-cairo python3-psutil python3-xdg dpkg-dev libgtk-4-dev libadwaita-1-dev

      - name: Test Debian build
        run: |
          cd packaging/debian
          ./build.sh

      - name: Verify Debian package
        run: |
          ls -la *.deb
          dpkg-deb --info sofl_*.deb

  test-arch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix git safe directory
        run: |
          git config --global --add safe.directory /home/runner/work/steam-online-fix-launcher/steam-online-fix-launcher

      - name: Test Arch source package creation
        run: |
          cd packaging/arch
          ./build.sh
          ls -la *.tar.gz

  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test version script
        run: |
          chmod +x scripts/*.sh
          VERSION=$(./scripts/get_version.sh)
          echo "Version: $VERSION"

      - name: Test update version script
        run: |
          ./scripts/update_version.sh "9.9.9"
          grep "version: '9.9.9'" meson.build
          # Reset to original
          git checkout -- meson.build packaging/*/DEBIAN/control packaging/*/PKGBUILD packaging/flatpak/*.yml 2>/dev/null || true
